[build]
  publish = "dist" # Adjust this to your build output directory
  command = "npm run build"

[build.environment]
  NODE_VERSION = "14.17.0" # Adjust this to your required Node version
  GO_VERSION = "1.19"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200