[build]
  publish = "dist" # Adjust this to your build output directory
  command = "npm run build"

[build.environment]
  NODE_VERSION = "16.0.0" # Update to a Node version that supports the ||= operator
  GO_VERSION = "1.19"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200